print('Hello my name is Sanzhar!')
print("hello tima!!")
print("hello tima ne boldei ;)!!")
print('Hi, my name is Janylai!')
print('Raimbek')
print('Hello Im Ramazan')
print('Hello Bema!!!')
print('My name is Igor!')
print('My name is Tariel')
print('Hello my name is Ksenia!')
print('Hello my name is Talgat')
print('Hello my name is Islam')
print('Hello my name is Nurmuhamed.')
print('hello im leon i love pony')
print('Hello my name is Manas')
print('Hello my name is Aibek!')
print('My name is Muha')
print('My name Tariel')
print('Hello my name is Aibek!')
print('My name is Muha')
print('My name is Adiltay')
print('CHIKA HELLO')
print('My name is Emil')
print('My name is Izat!')